[build]
  # Base directory for the build
  base = "."
  
  # Build command for the entire project
  command = "pnpm install && pnpm build:netlify"
  
  # Directory to publish (frontend build output)
  publish = "apps/web/dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # PNPM version
  PNPM_VERSION = "8"

# Netlify Functions configuration
[functions]
  # Directory where Netlify Functions are located
  directory = "netlify/functions"

# Redirects and rewrites
[[redirects]]
  # API routes to Netlify Functions
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
